Simple Calculator - four basic arithmetic operation
JefrenRA/calculator pull request #3
Opened 2023-02-15 06:38 UTC by merienxx

Task Accomplished:
Calculator object layout
Added event/actionPerformed for numbers and arithmetic operation buttons
Getting the result of math expression

2023-02-15 08:29 UTC, JefrenRA commented on calculator/src/main/java/com/tap/calculator/Main.java
> +		ScriptEngineManager scptEngMngr = new ScriptEngineManager();
Avoid using ScriptEngineManager and use simple arithmetic operation to compute given numbers

2023-02-15 08:33 UTC, JefrenRA commented on calculator/src/main/java/com/tap/calculator/Main.java
> +	//Declaration of objects
Apply encapsulation in local variables

2023-02-15 08:37 UTC, jeffbernardo reviewed
- handle null values (dont display null on the screen of calculator)
- clear history (clear the previous value of total if the user continue to input a digit)

2023-02-15 08:48 UTC, JefrenRA commented on calculator/src/main/java/com/tap/calculator/Main.java
> +	//Declaration of objects
Avoid inline variable initialization. Initialize variables in separate function call/method.

2023-02-15 09:01 UTC, JefrenRA requested changes
1. Apply OOP concepts:
for example: Encapsulation for the local variables, Abstraction for the arithmetic operations, etc
2. Enhance your code by applying single responsibility methods
3. Avoid using ScriptEngine to compute the arithmetic operations, use your own logic first for now.
4. Create different class and interfaces to apply OOP concepts

2023-02-17 03:29 UTC, jenyca reviewed
Add validations for the following scenarios:
- user should not be able to input consecutive dots in an expression 
- prevent user from inputting consecutive zeros if not decimal value
- prevent user from inputting arithmetic operations if not preceded by a number
- clear history

2023-02-17 03:32 UTC, JefrenRA requested changes

2023-02-17 03:32 UTC, JefrenRA commented on calculator/src/main/java/com/tap/calculator/ArithmeticOperations.java
> +		return String.valueOf(sum);
limit to two decimal places when the result has decimal point

2023-02-17 03:32 UTC, JefrenRA commented on calculator/src/main/java/com/tap/calculator/DeclareObjects.java
> +	protected JButton btnAdd, btnSub, btnMul, btnDiv, btnClearAll, btnBckSpc, btnDot, btnEqual;
avoid single line variable declaration

2023-02-17 03:32 UTC, JefrenRA commented on calculator/src/main/java/com/tap/calculator/DeclareObjects.java
> +	Font font = new Font("Century Gothic", Font.BOLD, 18);
make this final variable if the value will not be changed in entire program

2023-02-17 03:32 UTC, JefrenRA commented on calculator/src/main/java/com/tap/calculator/SolveExpression.java
> +			result = "0";
handle exception correctly

2023-02-17 03:32 UTC, JefrenRA commented on calculator/src/main/java/com/tap/calculator/DeclareObjects.java
> +	protected JLabel lblExp = new JLabel();
make variable private and create getter and setter for better encapsulation and to avoid data leak in the future

2023-02-23 07:28 UTC, JefrenRA requested changes

2023-02-23 07:28 UTC, JefrenRA commented on calculator/src/main/java/com/tap/calculator/beans/DeclareObjects.java
> +	public void setUpObjects() {
Should be called in the constructor of this class to avoid NullPointerException when this method was not be called

2023-02-23 07:28 UTC, JefrenRA commented on calculator/src/main/java/com/tap/calculator/events/ButtonClick.java
> +		decObj.setUpObjects();
This method should be called in the constructor of DecalareObjects class to avoid NullPointerException.

2023-02-23 07:28 UTC, JefrenRA commented on calculator/src/main/java/com/tap/calculator/events/ButtonClick.java
> +	public void testInput(String op) {
Don't forget to rename your method name

2023-02-23 08:59 UTC, JefrenRA approved these changes

2023-02-23 09:00 UTC, merged